version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      nx:
        patterns:
          - nx
          - '@nx/*'
      testing:
        patterns:
          - '@playwright/*'
          - vitest
          - '@vitest/*'
          - jest
          - 'jest-*'
